name: Integration testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [21.x, 25.x, 24.x] # 

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      # CRITICAL: Added checkout so your project files exist on the server
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Installing Node package manager
        run: npm i

      - name: Building project
        run: npm run build
